### ISSUE TITLE
Identify WQP characteristics matching calcium, chloride, and conductivity

### ISSUE THREAD

**Issue by lindsayplatt** [lindsayplatt/state-of-freshwater#1]
Use the existing `read_wqp_characteristics()` function and string matching functions to do it.

**Comment by lindsayplatt** [comment]
### Calcium

```r
library(tidyverse)
source('1_inventory/src/check_characteristics.R')
all_chars <- read_wqp_characteristics()

initial_calcium <- grep('calcium', all_chars, ignore.case = TRUE)
remaining_chars <- all_chars[-initial_calcium]

# Here are the ones returned (some are obviously going to get removed)
remaining_chars[grepl('CaC|Cal', remaining_chars)]
all_chars[initial_calcium]
```

From that code, these are the ones we need to say "in or out" for:

- "Acidity, hydrogen ion (H+) as CaCO3"
- "Acidity, mineral methyl orange (as CaCO3)"
- "Acidity, total, phenolphthalein (as CaCO3)"
- "Acid Neutralization Potential as CaCO3"
- "Alkalinity, Bicarbonate as CaCO3"
- "Alkalinity, Carbonate as CaCO3"
- "Alkalinity, Hydroxide as CaCO3"
- "Calcium"
- "Calcium-45"
- "Calcium as CaCO3"
- "Calcium carbonate"
- "Calcium hydroxide"
- "Calcium oxide"
- "Hardness, Calcium"                            
- "Saturation Index Calcite"

### Chloride

```r
library(tidyverse)
source('1_inventory/src/check_characteristics.R')
all_chars <- read_wqp_characteristics()

initial_chloride <- grep('chloride', all_chars, ignore.case = TRUE)
all_chars[initial_chloride]
```

- "4-Epianhydrotetracycline hydrochloride"
- "Allyl chloride"
- "Benzene Hexachloride, Alpha (BHC)"
- "Benzene Hexachloride, Beta (BHC)"
- "Benzene Hexachloride, Delta (BHC)"
- "Benzyl chloride"
- "Benzyldimethyldecylammonium chloride"
- "Benzyldimethyldodecylammonium chloride"
- "Benzyldimethylhexadecylammonium chloride"
- "Benzyldimethyloctylammonium chloride"
- "Benzyldimethylstearylammonium chloride"
- "Benzyldimethyltetradecylammonium chloride"
- "Buprenorphine hydrochloride"
- "Butyltin trichloride"
- "Carbon tetrachloride"
- "Chloride"
- "Dehydroaripiprazole hydrochloride"
- "Dibutyltin dichloride"
- "Ecgonine methyl ester hydrochloride"
- "Fluoxetine hydrochloride"
- "Formetanate hydrochloride"
- "Hydromorphone hydrochloride"
- "Imidacloprid desnitro-olefin hydrochloride"
- "Methylene chloride"
- "Piperidine, 1-(1-phenylcyclohexyl)-, hydrochloride"
- "Tributyltin chloride"
- "Tripentyltin chloride"
- "Tripropyltin chloride"
- "Vinyl chloride"                          
- "Vinyl chloride-d3"

### Specific conductivity

```r
library(tidyverse)
source('1_inventory/src/check_characteristics.R')
all_chars <- read_wqp_characteristics()

initial_conductivity <- grep('conduct', all_chars, ignore.case = TRUE)
all_chars[initial_conductivity]
```

- "Conductance"  
- "Conductivity"
- "Condition class, chemical (Conductivity/Salinity)"    
- "Specific conductivity"
- "Specific conductance"
- "Specific Conductance, Calculated/Measured Ratio"     
- "Specific conductivity***retired***use Specific conductance"

**Comment by hdugan** [comment]
Chloride is the easiest
- "Chloride"

SpC, I think just keep all of these for now. Will deal with 'conductivity' later. 
- "Conductance"
- "Conductivity"
- "Specific conductivity"
- "Specific conductance"
- "Specific Conductance, Calculated/Measured Ratio"
- "Specific conductivityretireduse Specific conductance"

Calcium
- "Calcium"

But now thinking we should also do alkalinity
- "Alkalinity, total"

**Comment by lindsayplatt** [comment]
There's also `Alkalinity` by itself?

**Comment by hdugan** [comment]
I know... but will all the specific alkalinities, I don't even know what that one means anymore.
